name: flutter_12
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  build_runner: ^2.4.4
  flutter:
    sdk: flutter
  freezed: ^2.3.4
  injectable: ^2.1.1
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
